name: Staging deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP }}.git
      - name: Fetch the full history of a shallow clone
        run: |
          git fetch --all --unshallow
      - name: Deploy app to Heroku
        run: |
          git push heroku master
